stages:
  preprocess:
    cmd: python src/preprocessing/preprocess.py
    deps:
      - src/preprocessing/preprocess.py
      - data/raw/housing.csv
    outs:
      - data/preprocessed_data.csv

  train:
    cmd: python src/model_trainer/model_trainer.py
    deps:
      - src/model_trainer/model_trainer.py
      - data/preprocessed_data.csv
    outs:
      - models/best_model.pkl

  evaluate:
    cmd: python src/evaluation/evaluate_model.py
    deps:
      - src/evaluation/evaluate_model.py
      - models/best_model.pkl
      - data/preprocessed_data.csv
    metrics:
      - metrics/test_metrics.json
    plots:
      - plots/prediction_vs_actual.png
